#!/usr/bin/env python3
"""
NLLB-200 LoRA Fine-Tuning for Bambara↔English/French
=====================================================
Fine-tunes facebook/nllb-200-distilled-600M with LoRA adapters
for improved Bambara translation quality.

Features:
  - LoRA on encoder + decoder attention (q_proj, v_proj)
  - Multi-directional: bam↔eng, bam↔fra (4 directions)
  - Resume from checkpoint
  - MPS (Apple Silicon) and CUDA support
  - Atomic checkpoint saves
  - Validation every epoch with BLEU scoring

Usage:
    python train_nllb_lora.py                          # Train on MPS
    python train_nllb_lora.py --device cuda             # Train on CUDA
    python train_nllb_lora.py --resume                  # Resume from checkpoint
    python train_nllb_lora.py --epochs 20 --lr 3e-4     # Custom hyperparams

Data:
    Reads from asr/nllb_data/nllb_train.jsonl and nllb_valid.jsonl
    (generated by prepare_nllb_data.py)
"""

import argparse
import json
import os
import signal
import sys
import time
from pathlib import Path

import torch
from torch.utils.data import Dataset, DataLoader


# ── NLLB Language Codes ──────────────────────────────────────────────

LANG_CODES = {
    "bam_Latn": "bam_Latn",
    "eng_Latn": "eng_Latn",
    "fra_Latn": "fra_Latn",
}


class NLLBTranslationDataset(Dataset):
    """Dataset for NLLB fine-tuning with parallel text pairs."""

    def __init__(self, path, tokenizer, max_length=128):
        self.pairs = []
        self.tokenizer = tokenizer
        self.max_length = max_length

        with open(path) as f:
            for line in f:
                if line.strip():
                    self.pairs.append(json.loads(line))

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, idx):
        pair = self.pairs[idx]
        src_text = pair["src"]
        tgt_text = pair["tgt"]
        src_lang = pair["src_lang"]
        tgt_lang = pair["tgt_lang"]

        # Set source language for tokenizer
        self.tokenizer.src_lang = src_lang

        # Tokenize source and target together (transformers v5+ API)
        model_inputs = self.tokenizer(
            text=src_text,
            text_target=tgt_text,
            max_length=self.max_length,
            truncation=True,
            padding="max_length",
            return_tensors="pt",
        )

        # Add forced BOS token for target language
        tgt_lang_id = self.tokenizer.convert_tokens_to_ids(tgt_lang)

        return {
            "input_ids": model_inputs["input_ids"].squeeze(0),
            "attention_mask": model_inputs["attention_mask"].squeeze(0),
            "labels": model_inputs["labels"].squeeze(0),
            "forced_bos_token_id": tgt_lang_id,
        }


def compute_bleu_score(predictions, references):
    """Simple BLEU-1 score for validation."""
    from collections import Counter

    scores = []
    for pred, ref in zip(predictions, references):
        pred_tokens = pred.lower().split()
        ref_tokens = ref.lower().split()
        if not pred_tokens or not ref_tokens:
            scores.append(0.0)
            continue

        pred_counts = Counter(pred_tokens)
        ref_counts = Counter(ref_tokens)

        # Clipped precision
        clipped = sum(min(pred_counts[w], ref_counts.get(w, 0)) for w in pred_counts)
        precision = clipped / len(pred_tokens) if pred_tokens else 0

        # Brevity penalty
        bp = min(1.0, len(pred_tokens) / len(ref_tokens)) if ref_tokens else 0
        scores.append(bp * precision)

    return sum(scores) / len(scores) if scores else 0.0


def validate(model, tokenizer, valid_loader, device):
    """Run validation and compute metrics."""
    model.eval()
    total_loss = 0
    num_batches = 0
    predictions = []
    references = []

    with torch.no_grad():
        for batch in valid_loader:
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)

            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                labels=labels,
            )
            total_loss += outputs.loss.item()
            num_batches += 1

            # Generate translations for BLEU (first 2 batches only for speed)
            if num_batches <= 2:
                generated = model.generate(
                    input_ids=input_ids,
                    attention_mask=attention_mask,
                    forced_bos_token_id=batch["forced_bos_token_id"][0].item(),
                    max_new_tokens=128,
                )
                for gen, lab in zip(generated, labels):
                    pred = tokenizer.decode(gen, skip_special_tokens=True)
                    ref = tokenizer.decode(lab[lab != -100], skip_special_tokens=True)
                    predictions.append(pred)
                    references.append(ref)

    avg_loss = total_loss / num_batches if num_batches else 0
    bleu = compute_bleu_score(predictions, references) if predictions else 0

    model.train()
    return avg_loss, bleu, predictions[:5], references[:5]


def save_checkpoint(path, model, optimizer, epoch, batch_idx, best_val, reason="epoch"):
    """Atomic checkpoint save."""
    from peft import get_peft_model_state_dict

    tmp = str(path) + ".tmp"
    torch.save({
        "lora_state": get_peft_model_state_dict(model),
        "optimizer_state": optimizer.state_dict(),
        "epoch": epoch,
        "batch_idx": batch_idx,
        "best_val_loss": best_val,
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "reason": reason,
    }, tmp)
    os.replace(tmp, path)
    print(f"  Checkpoint saved: {path} (reason={reason})")


def main():
    parser = argparse.ArgumentParser(description="NLLB-200 LoRA Fine-Tuning")
    parser.add_argument("--epochs", type=int, default=15)
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--lr", type=float, default=2e-4)
    parser.add_argument("--lora-rank", type=int, default=16)
    parser.add_argument("--lora-alpha", type=int, default=32)
    parser.add_argument("--max-length", type=int, default=128)
    parser.add_argument("--device", type=str, default="auto")
    parser.add_argument("--resume", action="store_true")
    parser.add_argument("--model-name", type=str, default="facebook/nllb-200-distilled-600M")
    parser.add_argument("--checkpoint-dir", type=str, default=str(Path(__file__).parent / "nllb_checkpoints"))
    parser.add_argument("--data-dir", type=str, default=str(Path(__file__).parent / "nllb_data"))
    args = parser.parse_args()

    # Device selection
    if args.device == "auto":
        if torch.cuda.is_available():
            device = torch.device("cuda")
        elif torch.backends.mps.is_available():
            device = torch.device("mps")
        else:
            device = torch.device("cpu")
    else:
        device = torch.device(args.device)

    print("=" * 60)
    print("NLLB-200 LoRA Fine-Tuning for Bambara")
    print("=" * 60)
    print(f"  Model:      {args.model_name}")
    print(f"  Device:     {device}")
    print(f"  Epochs:     {args.epochs}")
    print(f"  Batch size: {args.batch_size}")
    print(f"  LR:         {args.lr}")
    print(f"  LoRA rank:  {args.lora_rank}")
    print(f"  LoRA alpha: {args.lora_alpha}")
    print()

    # Load model and tokenizer
    from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
    from peft import LoraConfig, get_peft_model, TaskType

    print("Loading NLLB-200...")
    tokenizer = AutoTokenizer.from_pretrained(args.model_name)
    model = AutoModelForSeq2SeqLM.from_pretrained(args.model_name)

    # Apply LoRA
    lora_config = LoraConfig(
        task_type=TaskType.SEQ_2_SEQ_LM,
        r=args.lora_rank,
        lora_alpha=args.lora_alpha,
        lora_dropout=0.1,
        target_modules=["q_proj", "v_proj"],
        modules_to_save=None,
    )
    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()
    model.to(device)

    # Load data
    data_dir = Path(args.data_dir)
    train_dataset = NLLBTranslationDataset(data_dir / "nllb_train.jsonl", tokenizer, args.max_length)
    valid_dataset = NLLBTranslationDataset(data_dir / "nllb_valid.jsonl", tokenizer, args.max_length)

    print(f"  Train: {len(train_dataset)} pairs")
    print(f"  Valid: {len(valid_dataset)} pairs")

    train_loader = DataLoader(train_dataset, batch_size=args.batch_size, shuffle=True, num_workers=0)
    valid_loader = DataLoader(valid_dataset, batch_size=args.batch_size, shuffle=False, num_workers=0)

    # Optimizer
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=0.01)

    # Checkpoint directory
    ckpt_dir = Path(args.checkpoint_dir)
    ckpt_dir.mkdir(parents=True, exist_ok=True)
    ckpt_path = ckpt_dir / "nllb_lora_checkpoint.pt"
    best_path = ckpt_dir / "best_nllb_lora.pt"

    # Resume
    start_epoch = 0
    start_batch = 0
    best_val_loss = float("inf")

    if args.resume and ckpt_path.exists():
        print(f"  Resuming from {ckpt_path}")
        # weights_only=False required: checkpoint includes optimizer_state which
        # contains non-tensor objects (param groups, step counts) that need pickle.
        ckpt = torch.load(ckpt_path, map_location=device, weights_only=False)
        from peft import set_peft_model_state_dict
        set_peft_model_state_dict(model, ckpt["lora_state"])
        optimizer.load_state_dict(ckpt["optimizer_state"])
        start_epoch = ckpt["epoch"]
        start_batch = ckpt.get("batch_idx", 0)
        best_val_loss = ckpt.get("best_val_loss", float("inf"))
        print(f"  Resumed at epoch {start_epoch}, best_val={best_val_loss:.4f}")

    # Signal handler for graceful save
    interrupted = False

    def handle_signal(signum, frame):
        nonlocal interrupted
        print(f"\n  Signal {signum} received, saving checkpoint...")
        interrupted = True

    signal.signal(signal.SIGTERM, handle_signal)
    signal.signal(signal.SIGINT, handle_signal)

    # Training loop
    print(f"\n{'='*60}")
    print(f"Training started")
    print(f"{'='*60}")

    for epoch in range(start_epoch, args.epochs):
        model.train()
        epoch_loss = 0
        num_batches = 0
        t0 = time.time()

        for batch_idx, batch in enumerate(train_loader):
            if interrupted:
                save_checkpoint(ckpt_path, model, optimizer, epoch, batch_idx, best_val_loss, "interrupt")
                print("Interrupted. Checkpoint saved.")
                sys.exit(0)

            # Skip batches if resuming mid-epoch
            if epoch == start_epoch and batch_idx < start_batch:
                continue

            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)

            # Replace padding token id with -100 so it's ignored in loss
            labels[labels == tokenizer.pad_token_id] = -100

            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                labels=labels,
            )

            loss = outputs.loss
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            optimizer.zero_grad()

            epoch_loss += loss.item()
            num_batches += 1

            if batch_idx % 50 == 0:
                avg = epoch_loss / num_batches
                elapsed = time.time() - t0
                speed = num_batches / elapsed if elapsed > 0 else 0
                print(f"  E{epoch+1} B{batch_idx}/{len(train_loader)} | loss={avg:.4f} | {speed:.1f} b/s")

        # Epoch complete
        train_loss = epoch_loss / num_batches if num_batches else 0
        elapsed = time.time() - t0

        # Validation
        val_loss, bleu, sample_preds, sample_refs = validate(model, tokenizer, valid_loader, device)

        print(f"\n  Epoch {epoch+1}/{args.epochs} | train_loss={train_loss:.4f} | val_loss={val_loss:.4f} | BLEU-1={bleu:.3f} | {elapsed:.0f}s")

        # Show samples
        for pred, ref in zip(sample_preds[:3], sample_refs[:3]):
            print(f"    pred: {pred[:60]}")
            print(f"    ref:  {ref[:60]}")
            print()

        # Save checkpoint
        save_checkpoint(ckpt_path, model, optimizer, epoch + 1, 0, best_val_loss, "epoch")

        # Save best model
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            save_checkpoint(best_path, model, optimizer, epoch + 1, 0, best_val_loss, "best")
            print(f"  New best model! val_loss={best_val_loss:.4f}")

    print(f"\nTraining complete. Best val_loss={best_val_loss:.4f}")
    print(f"Best model: {best_path}")

    # Export merged model for deployment
    print("\nExporting merged model for deployment...")
    merged_dir = ckpt_dir / "nllb_bambara_merged"
    model = model.merge_and_unload()
    model.save_pretrained(str(merged_dir))
    tokenizer.save_pretrained(str(merged_dir))
    print(f"Merged model saved to: {merged_dir}")


if __name__ == "__main__":
    main()
